# Generated by Django 6.1 on 2026-08-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="university",
            options={"ordering": ["-ranking"], "verbose_name_plural": "Universities"},
        ),
    ]
